# Indexing,Slicing and Iterations on Array
we will focus on 1D and 2D Arrays only.

In [1]:
import numpy as np

## Indexing of Array
1)Array indexing is the same as accessing an array element.<br>
2)You can access an array element by referring to its index number.<br>
3)The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.<br>

### Accesing the 1D Array.

In [2]:
a = np.array([1,2,3,4,5,6])

In [7]:
for i in range(len(a)):
    print('index',i,'element',a[i])

index 0 element 1
index 1 element 2
index 2 element 3
index 3 element 4
index 4 element 5
index 5 element 6


### Accesing the 2D Array

In [8]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
for i in range(len(b)):
    print('index',i,'element',b[i])

index 0 element [1 2 3]
index 1 element [4 5 6]
index 2 element [7 8 9]


In [13]:
for i in range(len(b)):
    for j in range(len(b[i])):
            print('index',i,j,'element',b[i,j])

index 0 0 element 1
index 0 1 element 2
index 0 2 element 3
index 1 0 element 4
index 1 1 element 5
index 1 2 element 6
index 2 0 element 7
index 2 1 element 8
index 2 2 element 9


## The nditer Function to iterate on Arrays

In [15]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


In [14]:
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6
7
8
9


## Slicing of Array 
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

### Slicing of 1D Array

In [17]:
print(a)

[1 2 3 4 5 6]


In [20]:
print(a[2:5])
print(a[:5])
print(a[2:])
print(a[1:4:2])

[3 4 5]
[1 2 3 4 5]
[3 4 5 6]
[2 4]


### Slicing of 2D Array

In [21]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(b[1:3,1:3])

[[5 6]
 [8 9]]


In [23]:
print(b[:2])

[[1 2 3]
 [4 5 6]]


In [26]:
print(b[0:3,1:3])

[[2 3]
 [5 6]
 [8 9]]
