# Introduction to Array with numpy
NumPy is used to work with arrays. <br>
The array object in NumPy is called ndarray.<br>
We can create a NumPy ndarray object by using the array() function.<br>

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.21.5


## 0-Dimension Array
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [7]:
a = np.array(42)

In [8]:
print(a)
print(type(a))

42
<class 'numpy.ndarray'>


## 1-Dimension Array
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.<br>
These are the most common and basic arrays.<br>

In [10]:
b = np.array([1,2,3,4])
print(b)

[1 2 3 4]


## 2-Dimension Array
An array that has 1-D arrays as its elements is called a 2-D array.<br>
These are often used to represent matrix or 2nd order tensors.<br>

In [13]:
c = np.array([[1,2,3,4],[4,5,6,7]])
print(c)

[[1 2 3 4]
 [4 5 6 7]]


## 3-Dimension Array
An array that has 2-D arrays (matrices) as its elements is called 3-D array.<br>
These are often used to represent a 3rd order tensor.<br>

In [16]:
d = np.array([[[1,2,3,4],[5,6,7,8]],
              [[1,2,3,4],[5,6,7,8]]])
print(d)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


## Check the Dimension of array
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [18]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Define array the dimension specifying.
An array can have any number of dimensions.<br>
When the array is created, you can define the number of dimensions by using the ndmin argument.<br>

In [63]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Create Following
1) array with one,zero<br>
2) array with random number<br>
3) array with identity matrics<br>
4) array with arange function<br>
5) array with lenspace function<br>
6) array with like one,zero<br>

# Array with ones
np.ones(shape, dtype=None, order='C', *, like=None)<br>
Return a new array of given shape and type, filled with ones.<br>

Parameters<br>
shape = int or sequence of ints<br>
Shape of the new array, e.g., (2, 3) or 2.<br>

dtype = data-type, optional <br>
The desired data-type for the array, e.g., np.int8. Default is np.float64.<br>

In [33]:
# array with one
e = np.ones(5)
e

array([1., 1., 1., 1., 1.])

In [35]:
f = np.ones((5,),dtype = int)
f

array([1, 1, 1, 1, 1])

In [38]:
g = np.ones((2,3),dtype=int)
g

array([[1, 1, 1],
       [1, 1, 1]])

# Array with zeros
np.zeros(shape, dtype=None, order='C', *, like=None)<br>
Return a new array of given shape and type, filled with zeros.<br>

Parameters<br>
shape = int or sequence of ints<br>
Shape of the new array, e.g., (2, 3) or 2.<br>

dtype = data-type, optional <br>
The desired data-type for the array, e.g., np.int8. Default is np.float64.<br>

In [39]:
h = np.zeros(5)
h

array([0., 0., 0., 0., 0.])

In [41]:
i = np.zeros((2,4),dtype = int)
i

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

# Array with fill values
numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)<br>
Return a new array of given shape and type, filled with fill_value.<br>

Parameters <br>
shape = int or sequence of ints <br>
Shape of the new array, e.g., (2, 3) or 2.<br>

fill_value scalar or array_like<br>
Fill value.<br>

dtype = data-type, optional<br>
The desired data-type for the array The default, None, means<br>
np.array(fill_value).dtype.<br>

In [44]:
j = np.full((2,4),np.inf) # np.inf means infinity
j

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [46]:
k = np.full((3,4),5)
k

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [47]:
l = np.full((3,4),'Mayu')
l

array([['Mayu', 'Mayu', 'Mayu', 'Mayu'],
       ['Mayu', 'Mayu', 'Mayu', 'Mayu'],
       ['Mayu', 'Mayu', 'Mayu', 'Mayu']], dtype='<U4')

# ones Like
numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)<br>
Return an array of ones with the same shape and type as a given array.<br>

Parameters<br>
a array_like<br>
The shape and data-type of a define these same attributes of the returned array.<br>

dtypedata-type, optional<br>
Overrides the data type of the result.<br>

In [48]:
x = np.arange(6)
x = x.reshape((2, 3))
x


array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
np.ones_like(x)


array([[1, 1, 1],
       [1, 1, 1]])

# zeros Like
numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)<br>
Return an array of zeros with the same shape and type as a given array.<br>

Parameters<br>
a array_like<br>
The shape and data-type of a define these same attributes of the returned array.<br>

dtype data-type, optional<br>
Overrides the data type of the result.<br>

In [53]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

# Identity matrics
numpy.identity(n, dtype=None, *, like=None)<br>
Return the identity array.<br>

The identity array is a square array with ones on the main diagonal.<br>

Parameters<br>
n int<br>
Number of rows (and columns) in n x n output.<br>

dtype data-type, optional<br>
Data-type of the output. Defaults to float.<br>

In [54]:
m = np.identity(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
n = np.identity(3,dtype = int)
n

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Arange Function
numpy.arange(start,stop, step,dtype=None, *, like=None)<br>
Return evenly spaced values within a given interval.<br>

arange can be called with a varying number of positional arguments:<br>

arange(stop): Values are generated within the  interval (0, stop) (in other words, the interval including start but excluding <br>stop)<br>

arange(start, stop): Values are generated within the interval (start, stop).(in other words, the interval including start but <br>excluding stop)<br>

arange(start, stop, step) Values are generated within the interval (start, stop), with spacing between values given by step.<br>
(in other words, the interval including start but excluding stop with step as size)<br>

For integer arguments the function is roughly equivalent to the Python built-in range, but returns an ndarray rather than a <br>range instance.

In [59]:
o = np.arange(5,10,1)
o

array([5, 6, 7, 8, 9])

In [60]:
p = np.arange(10,20,3)
p

array([10, 13, 16, 19])

# linspace Function
numpy.linspace
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

In [62]:
q = np.linspace(5,20,15)
q

array([ 5.        ,  6.07142857,  7.14285714,  8.21428571,  9.28571429,
       10.35714286, 11.42857143, 12.5       , 13.57142857, 14.64285714,
       15.71428571, 16.78571429, 17.85714286, 18.92857143, 20.        ])